# DEV - Autoencoder

- Overview: try pca, kmeans, **autoencoder**
- Idea: anomalies compare to predicted class
- Thought: but these are alread principal components...

**Hyperparameter Tuning**

When training a machine learning model it is helpful to find the optimal values for hyperparameters, parameters set before training begins.  These are not learned parameters like the coefficents of a model.  Rather than manually iterating these parameters we want to sequently test and focus in on optimal values.  The focusing part of the iterations is done in BQML by utilizing the [Vertex AI Vizier](https://cloud.google.com/vertex-ai/docs/vizier/overview) service by default.

Each `MODEL_TYPE` in BQML has parameters than can be tuned as [listed here](https://cloud.google.com/bigquery-ml/docs/reference/standard-sql/bigqueryml-hyperparameter-tuning#hyperparameters_and_objectives). 

**Prerequisites:**
-  01 - BigQuery - Table Data Source

**Resources:**
-  [BigQuery ML (BQML) Overview](https://cloud.google.com/bigquery-ml/docs/introduction)
-  [Overview of BQML methods and workflows](https://cloud.google.com/bigquery-ml/docs/reference/standard-sql/bigqueryml-syntax-e2e-journey)

**Conceptual Flow & Workflow**

---
## Setup

inputs:

In [1]:
project = !gcloud config get-value project
PROJECT_ID = project[0]
PROJECT_ID

'statmike-mlops-349915'

In [2]:
REGION = 'us-central1'
EXPERIMENT = 'autoencoder'
SERIES = '03'

# source data
BQ_PROJECT = PROJECT_ID
BQ_DATASET = 'fraud'
BQ_TABLE = 'fraud_prepped'

# Resources for serving BigQuery Model Exports
TF_DEPLOY_IMAGE = 'us-docker.pkg.dev/vertex-ai/prediction/tf2-cpu.2-3:latest'
XGB_DEPLOY_IMAGE = 'us-docker.pkg.dev/vertex-ai/prediction/xgboost-cpu.0-82:latest'

# Model Training
VAR_TARGET = 'Class'
VAR_OMIT = 'transaction_id' # add more variables to the string with space delimiters

packages:

In [3]:
from google.cloud import bigquery
from google.cloud import aiplatform
from datetime import datetime
import matplotlib.pyplot as plt

clients:

In [4]:
bq = bigquery.Client()
aiplatform.init(project=PROJECT_ID, location=REGION)

parameters:

In [5]:
TIMESTAMP = datetime.now().strftime("%Y%m%d%H%M%S")
BUCKET = PROJECT_ID
URI = f"gs://{BUCKET}/{SERIES}/{EXPERIMENT}"
RUN_NAME = f'run-{TIMESTAMP}'

BQ_MODEL = f'{SERIES}_{EXPERIMENT}_{TIMESTAMP}'

---
## This Run

In [6]:
print(f'This run with create BQML model: {BQ_PROJECT}.{BQ_DATASET}.{BQ_MODEL}')
print(f'The Timestamp Is: {TIMESTAMP}')

This run with create BQML model: statmike-mlops-349915.fraud.03_autoencoder_20221005002145
The Timestamp Is: 20221005002145

---
## Train Model

Use BigQuery ML to train multiclass logistic regression model:
- [Autoencoder](https://cloud.google.com/bigquery-ml/docs/reference/standard-sql/bigqueryml-syntax-create-autoencoder) with BigQuery ML (BQML)
- This uses the `splits` column that notebook `01` created
- `data_split_method = CUSTOM` uses the column in `data_split_col` to assign `TRAIN`, `EVAL`, and `TEST` data splits.
    - the `CASE` statement maps the validation data to `EVAL` as expected by hyperparameter tuning (rather than `VALIDATE`)
    - note that this is different behavior for `data_split_col` with hyperparameter tuning than without hyperparameter tuning
    - hyperparameter suggestions are based on the metric calculated with the evaluation data at each intermediate step

In [ ]:
query = f"""
CREATE OR REPLACE MODEL `{BQ_PROJECT}.{BQ_DATASET}.{BQ_MODEL}`
OPTIONS (
        model_type = 'AUTOENCODER',
        activation_fn = HPARAM_CANDIDATES(['RELU', 'TANH']),
        batch_size = HPARAM_RANGE(15, 100),
        dropout = HPARAM_RANGE(.1, .9),
        early_stop = TRUE,
        hidden_units =HPARAM_CANDIDATES([struct([64, 8, 64]), struct([128, 64, 8, 64, 128]), struct([256, 64, 8, 64, 128])]),
        max_iterations = 50,
        min_rel_progress = 0.0001,
        optimizer = HPARAM_CANDIDATES(['SGD', 'ADAM']),
        data_split_col = 'custom_splits',
        data_split_method = 'CUSTOM',
        hparam_tuning_algorithm = 'VIZIER_DEFAULT',
        hparam_tuning_objectives = ['mean_absolute_error'],
        num_trials = 40,
        max_parallel_trials = 5
    ) AS
SELECT * EXCEPT({','.join(VAR_OMIT.split())}, splits, {VAR_TARGET}),
    CASE
        WHEN splits = 'VALIDATE' THEN 'EVAL'
        ELSE splits
    END AS custom_splits
FROM `{BQ_PROJECT}.{BQ_DATASET}.{BQ_TABLE}`
"""
job = bq.query(query = query)
job.result()

In [ ]:
(job.ended-job.started).total_seconds()

In [12]:
feature_info = bq.query(
    query = f"""
        SELECT *
        FROM ML.FEATURE_INFO(MODEL `{BQ_PROJECT}.{BQ_DATASET}.{BQ_MODEL}`)
        """
).to_dataframe()
feature_info

,input,min,max,mean,median,stddev,category_count,null_count,dimension
0,Amount,0.000000,25691.160000,87.977372,21.610000,242.055780,NaN,0,NaN
1,Time,0.000000,172792.000000,94865.379565,85104.000000,47485.090893,NaN,0,NaN
2,V1,-56.407510,2.454930,0.002530,0.004484,1.954377,NaN,0,NaN
3,V10,-24.588262,23.745136,0.000380,-0.098514,1.088245,NaN,0,NaN
4,V11,-4.797473,12.018913,0.000876,-0.039446,1.021200,NaN,0,NaN
5,V12,-18.683715,7.848392,-0.000217,0.135537,1.001530,NaN,0,NaN
6,V13,-5.791881,7.126883,-0.000889,-0.024213,0.995349,NaN,0,NaN
7,V14,-19.214325,10.526766,-0.000488,0.039000,0.960284,NaN,0,NaN
8,V15,-4.498945,8.877742,0.000631,0.051657,0.915896,NaN,0,NaN
9,V16,-14.129855,17.315112,-0.000698,0.066888,0.876710,NaN,0,NaN
10,V17,-25.162799,9.253526,-0.000113,-0.072286,0.853091,NaN,0,NaN
11,V18,-9.498746,4.295648,0.000021,-0.001247,0.839570,NaN,0,NaN
12,V19,-4.619034,5.591971,0.000671,0.000404,0.812645,NaN,0,NaN
13,V2,-72.715728,22.057729,0.000738,0.051223,1.636207,NaN,0,NaN
14,V20,-54.497720,26.237391,-0.001606,-0.063519,0.763035,NaN,0,NaN
15,V21,-34.830382,27.202839,0.000461,-0.027563,0.735514,NaN,0,NaN
16,V22,-8.887017,10.503090,0.001016,-0.001874,0.724883,NaN,0,NaN
17,V23,-36.666000,22.528412,-0.000068,-0.011170,0.622001,NaN,0,NaN
18,V24,-2.824849,4.584549,0.000171,0.037117,0.605825,NaN,0,NaN
19,V25,-7.495741,7.519589,-0.000449,0.019408,0.520229,NaN,0,NaN
20,V26,-2.068561,3.517346,-0.000001,-0.055390,0.482213,NaN,0,NaN
21,V27,-22.565679,31.612198,-0.000145,0.001544,0.405117,NaN,0,NaN
22,V28,-15.430084,33.847808,0.000371,0.010740,0.333738,NaN,0,NaN
23,V3,-48.325589,9.382558,-0.000786,0.168159,1.514746,NaN,0,NaN
24,V4,-5.683171,16.491217,0.001577,-0.048208,1.416648,NaN,0,NaN
25,V5,-113.743307,34.801666,0.000619,-0.041387,1.380527,NaN,0,NaN
26,V6,-26.160506,73.301626,0.000317,-0.275783,1.331948,NaN,0,NaN
27,V7,-43.557242,120.589494,-0.000747,0.036847,1.239360,NaN,0,NaN
28,V8,-73.216718,20.007208,-0.001289,0.019443,1.197096,NaN,0,NaN
29,V9,-13.320155,15.594995,0.000007,-0.053919,1.098390,NaN,0,NaN
30,custom_splits,NaN,NaN,NaN,NaN,NaN,3.0,0,NaN

In [13]:
trials = bq.query(
    query = f"""
        SELECT *
        FROM ML.TRIAL_INFO(MODEL `{BQ_PROJECT}.{BQ_DATASET}.{BQ_MODEL}`)
        """
).to_dataframe()
trials

,trial_id,hyperparameters,hparam_tuning_evaluation_metrics,training_loss,eval_loss,status,error_message,is_optimal
0,1,"{'hidden_units': [64, 8, 64], 'batch_size': 32...",{'mean_absolute_error': 0.33118679988068384},0.010028,0.000017,SUCCEEDED,None,False
1,2,"{'hidden_units': [128, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.4067171805501922},0.014132,0.000020,SUCCEEDED,None,False
2,3,"{'hidden_units': [256, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.2495703042107863},0.009010,0.000013,SUCCEEDED,None,False
3,4,"{'hidden_units': [256, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.5526720246906225},0.028767,0.000029,SUCCEEDED,None,False
4,5,"{'hidden_units': [64, 8, 64], 'batch_size': 55...",{'mean_absolute_error': 0.27614641235369064},0.002907,0.000014,SUCCEEDED,None,False
5,6,"{'hidden_units': [256, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.25781977268588313},0.009239,0.000013,SUCCEEDED,None,False
6,7,"{'hidden_units': [256, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.2557016759934491},0.006807,0.000013,SUCCEEDED,None,False
7,8,"{'hidden_units': [256, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.23901097992636666},0.004654,0.000013,SUCCEEDED,None,True
8,9,"{'hidden_units': [64, 8, 64], 'batch_size': 15...",{'mean_absolute_error': 0.2734102713835557},0.007059,0.000014,SUCCEEDED,None,False
9,10,"{'hidden_units': [256, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.25222028827463244},0.002257,0.000013,SUCCEEDED,None,False
10,11,"{'hidden_units': [256, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.23909554143974648},0.001294,0.000013,SUCCEEDED,None,False
11,12,"{'hidden_units': [256, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.24908294494206984},0.002671,0.000013,SUCCEEDED,None,False
12,13,"{'hidden_units': [256, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.25502751712733124},0.000987,0.000013,SUCCEEDED,None,False
13,14,"{'hidden_units': [256, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.24748730853911596},0.001855,0.000013,SUCCEEDED,None,False
14,15,"{'hidden_units': [256, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.24258203936209446},0.000881,0.000013,SUCCEEDED,None,False
15,16,"{'hidden_units': [256, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.2489431414397597},0.001814,0.000013,SUCCEEDED,None,False
16,17,"{'hidden_units': [256, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.4212584529344462},0.006891,0.000020,SUCCEEDED,None,False
17,18,"{'hidden_units': [256, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.2533355273332397},0.005481,0.000013,SUCCEEDED,None,False
18,19,"{'hidden_units': [256, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.24919771758931222},0.002408,0.000013,SUCCEEDED,None,False
19,20,"{'hidden_units': [256, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.35371771817504166},0.002350,0.000017,SUCCEEDED,None,False
20,21,"{'hidden_units': [128, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.24383346589342994},0.001028,0.000013,SUCCEEDED,None,False
21,22,"{'hidden_units': [256, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.259788306554349},0.003173,0.000013,SUCCEEDED,None,False
22,23,"{'hidden_units': [256, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.35884287403955595},0.004988,0.000017,SUCCEEDED,None,False
23,24,"{'hidden_units': [256, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.2545426572587503},0.004627,0.000013,SUCCEEDED,None,False
24,25,"{'hidden_units': [256, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.25382218242591625},0.002482,0.000013,SUCCEEDED,None,False
25,26,"{'hidden_units': [128, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.2471234891438768},0.002016,0.000013,SUCCEEDED,None,False
26,27,"{'hidden_units': [256, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.24508291284275757},0.002547,0.000013,SUCCEEDED,None,False
27,28,"{'hidden_units': [256, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.24458826948531442},0.001256,0.000014,SUCCEEDED,None,False
28,29,"{'hidden_units': [128, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.240483472946148},0.001461,0.000013,SUCCEEDED,None,False
29,30,"{'hidden_units': [256, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.2540844054834736},0.002127,0.000013,SUCCEEDED,None,False
30,31,"{'hidden_units': [64, 8, 64], 'batch_size': 80...",{'mean_absolute_error': 0.2926526425680805},0.001440,0.000015,SUCCEEDED,None,False
31,32,"{'hidden_units': [256, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.4282172651150911},0.004380,0.000022,SUCCEEDED,None,False
32,33,"{'hidden_units': [64, 8, 64], 'batch_size': 97...",{'mean_absolute_error': 0.29872918559906453},0.002402,0.000015,SUCCEEDED,None,False
33,34,"{'hidden_units': [128, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.25282959088043083},0.002892,0.000013,SUCCEEDED,None,False
34,35,"{'hidden_units': [128, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.24381835629686072},0.001081,0.000013,SUCCEEDED,None,False
35,36,"{'hidden_units': [256, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.24925772305400645},0.000995,0.000013,SUCCEEDED,None,False
36,37,"{'hidden_units': [128, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.24659052908854218},0.000760,0.000013,SUCCEEDED,None,False
37,38,"{'hidden_units': [128, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.24284198980447275},0.001636,0.000013,SUCCEEDED,None,False
38,39,"{'hidden_units': [256, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.3296528482796262},0.003095,0.000016,SUCCEEDED,None,False
39,40,"{'hidden_units': [128, 64, 8, 64, 128], 'batch...",{'mean_absolute_error': 0.24815189067383886},0.002093,0.000013,SUCCEEDED,None,False

In [15]:
eval = bq.query(
    query = f"""
        SELECT *
        FROM ML.EVALUATE(MODEL `{BQ_PROJECT}.{BQ_DATASET}.{BQ_MODEL}`)
        """
).to_dataframe()
eval

    trial_id  mean_absolute_error  mean_squared_error  mean_squared_log_error
0          1             0.327874            0.425683                0.039454
1          2             0.403131            0.537158                0.033200
2          3             0.245562            0.338232                0.025611
3          4             0.549455            0.803867                0.118270
4          5             0.272348            0.364448                0.029854
5          6             0.253953            0.346932                0.027248
6          7             0.252237            0.347530                0.026611
7          8             0.235408            0.332809                0.024274
8          9             0.270077            0.370347                0.030345
9         10             0.248972            0.342107                0.026140
10        11             0.235842            0.335890                0.024717
11        12             0.245608            0.340120                0.025553
12        13             0.251599            0.352497                0.026975
13        14             0.243651            0.343676                0.025893
14        15             0.238937            0.338990                0.025194
15        16             0.245354            0.340493                0.025817
16        17             0.418523            0.531519                0.042363
17        18             0.249803            0.346393                0.026508
18        19             0.245665            0.341841                0.026233
19        20             0.350113            0.449402                0.043379
20        21             0.240147            0.336309                0.025034
21        22             0.255929            0.352619                0.028030
22        23             0.354932            0.455989                0.044325
23        24             0.251196            0.344818                0.026450
24        25             0.250207            0.343037                0.025886
25        26             0.243483            0.342863                0.026170
26        27             0.241355            0.339064                0.025367
27        28             0.241127            0.355254                0.026937
28        29             0.236562            0.333928                0.024149
29        30             0.250848            0.345965                0.025998
30        31             0.289912            0.391854                0.033657
31        32             0.425010            0.577090                0.045766
32        33             0.295318            0.388204                0.033282
33        34             0.248635            0.348309                0.026081
34        35             0.240216            0.335801                0.024562
35        36             0.245411            0.340907                0.025705
36        37             0.243413            0.341597                0.025824
37        38             0.238972            0.339264                0.024953
38        39             0.326337            0.411455                0.038454
39        40             0.244800            0.340209                0.025986

In [ ]:
query = f"""
SELECT *
FROM ML.PREDICT (MODEL `{BQ_PROJECT}.{BQ_DATASET}.{BQ_MODEL}`,(
    SELECT *
    FROM `{BQ_PROJECT}.{BQ_DATASET}.{BQ_TABLE}`
    WHERE splits = 'TEST')
  )
"""
pred = bq.query(query = query).to_dataframe()

In [ ]:
pred.head()

In [21]:
query = f"""
SELECT *
FROM ML.DETECT_ANOMALIES (
    MODEL `{BQ_PROJECT}.{BQ_DATASET}.{BQ_MODEL}`,
    STRUCT (0.01 AS contamination),
    (SELECT *
    FROM `{BQ_PROJECT}.{BQ_DATASET}.{BQ_TABLE}`
    WHERE splits = 'TEST')
  )
"""
anomalies = bq.query(query = query).to_dataframe()

In [ ]:
anomalies

In [ ]:
query = f"""
WITH ANOMALIES AS (
        SELECT is_anomaly, {VAR_TARGET}
        FROM ML.DETECT_ANOMALIES (
            MODEL `{BQ_PROJECT}.{BQ_DATASET}.{BQ_MODEL}`,
            STRUCT (0.001 AS contamination),
            (SELECT *
            FROM `{BQ_PROJECT}.{BQ_DATASET}.{BQ_TABLE}`
            WHERE splits = 'TEST')
          )
      )
SELECT is_anomaly, {VAR_TARGET}, count(*) as count
FROM ANOMALIES
GROUP BY is_anomaly, {VAR_TARGET}
"""
bq.query(query = query).to_dataframe()